/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/bmc/about": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Firmware, daemon, kernel and board identity
     * @description Legacy form: `GET /api/bmc?opt=get&type=about` with the same parameters in the query string. That form answers `{"response":[{"result":…}]}` and puts a refusal's message in `result`; this path answers the bare result and a refusal as `application/problem+json`.
     */
    get: operations["getAbout"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/bmc/config": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Everything configured on this board, as one document
     * @description Legacy form: `GET /api/bmc?opt=get&type=config` with the same parameters in the query string. That form answers `{"response":[{"result":…}]}` and puts a refusal's message in `result`; this path answers the bare result and a refusal as `application/problem+json`.
     */
    get: operations["getConfig"];
    put?: never;
    /**
     * Apply an exported configuration; reports per field
     * @description Legacy form: `GET /api/bmc?opt=set&type=config` with the same parameters in the query string. That form answers `{"response":[{"result":…}]}` and puts a refusal's message in `result`; this path answers the bare result and a refusal as `application/problem+json`.
     */
    post: operations["postConfig"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/bmc/cooling": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Cooling devices with their setpoints
     * @description Legacy form: `GET /api/bmc?opt=get&type=cooling` with the same parameters in the query string. That form answers `{"response":[{"result":…}]}` and puts a refusal's message in `result`; this path answers the bare result and a refusal as `application/problem+json`.
     */
    get: operations["getCooling"];
    put?: never;
    /**
     * Set a cooling device's step
     * @description Legacy form: `GET /api/bmc?opt=set&type=cooling` with the same parameters in the query string. That form answers `{"response":[{"result":…}]}` and puts a refusal's message in `result`; this path answers the bare result and a refusal as `application/problem+json`.
     */
    post: operations["postCooling"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/bmc/firmware/available": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Every enabled source's candidates; `refresh=1` re-polls behind the answer
     * @description Legacy form: `GET /api/bmc?opt=get&type=firmware_available` with the same parameters in the query string. That form answers `{"response":[{"result":…}]}` and puts a refusal's message in `result`; this path answers the bare result and a refusal as `application/problem+json`.
     */
    get: operations["getFirmwareAvailable"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/bmc/firmware/check": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Whether a newer release exists, per channel
     * @description Legacy form: `GET /api/bmc?opt=get&type=update_check` with the same parameters in the query string. That form answers `{"response":[{"result":…}]}` and puts a refusal's message in `result`; this path answers the bare result and a refusal as `application/problem+json`.
     */
    get: operations["getFirmwareCheck"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/bmc/firmware/install": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Stage a version from a source for the next boot
     * @description Legacy form: `GET /api/bmc?opt=set&type=firmware_install` with the same parameters in the query string. That form answers `{"response":[{"result":…}]}` and puts a refusal's message in `result`; this path answers the bare result and a refusal as `application/problem+json`.
     */
    post: operations["postFirmwareInstall"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/bmc/firmware/slots": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * The A/B slots: running, rollback, what is staged, the last promotion
     * @description Legacy form: `GET /api/bmc?opt=get&type=firmware_slots` with the same parameters in the query string. That form answers `{"response":[{"result":…}]}` and puts a refusal's message in `result`; this path answers the bare result and a refusal as `application/problem+json`.
     */
    get: operations["getFirmwareSlots"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/bmc/firmware/sources": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Where the board looks for firmware
     * @description Legacy form: `GET /api/bmc?opt=get&type=firmware_sources` with the same parameters in the query string. That form answers `{"response":[{"result":…}]}` and puts a refusal's message in `result`; this path answers the bare result and a refusal as `application/problem+json`.
     */
    get: operations["getFirmwareSources"];
    put?: never;
    /**
     * Replace the firmware sources
     * @description Legacy form: `GET /api/bmc?opt=set&type=firmware_sources` with the same parameters in the query string. That form answers `{"response":[{"result":…}]}` and puts a refusal's message in `result`; this path answers the bare result and a refusal as `application/problem+json`.
     */
    post: operations["postFirmwareSources"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/bmc/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * The board's own condition: uptime, load, memory, NAND, clock
     * @description Legacy form: `GET /api/bmc?opt=get&type=health` with the same parameters in the query string. That form answers `{"response":[{"result":…}]}` and puts a refusal's message in `result`; this path answers the bare result and a refusal as `application/problem+json`.
     */
    get: operations["getHealth"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/bmc/hostname": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * The board's name, live and after the next boot
     * @description Legacy form: `GET /api/bmc?opt=get&type=hostname` with the same parameters in the query string. That form answers `{"response":[{"result":…}]}` and puts a refusal's message in `result`; this path answers the bare result and a refusal as `application/problem+json`.
     */
    get: operations["getHostname"];
    put?: never;
    /**
     * Rename the board; the metrics instance label changes with it
     * @description Legacy form: `GET /api/bmc?opt=set&type=hostname` with the same parameters in the query string. That form answers `{"response":[{"result":…}]}` and puts a refusal's message in `result`; this path answers the bare result and a refusal as `application/problem+json`.
     */
    post: operations["postHostname"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/bmc/info": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Storage and interfaces, as the Overview page reads them
     * @description Legacy form: `GET /api/bmc?opt=get&type=info` with the same parameters in the query string. That form answers `{"response":[{"result":…}]}` and puts a refusal's message in `result`; this path answers the bare result and a refusal as `application/problem+json`.
     */
    get: operations["getInfo"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/bmc/network": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Interfaces and switch ports
     * @description Legacy form: `GET /api/bmc?opt=get&type=network` with the same parameters in the query string. That form answers `{"response":[{"result":…}]}` and puts a refusal's message in `result`; this path answers the bare result and a refusal as `application/problem+json`.
     */
    get: operations["getNetwork"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/bmc/network/reset": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Reset the network configuration
     * @description Legacy form: `GET /api/bmc?opt=set&type=network` with the same parameters in the query string. That form answers `{"response":[{"result":…}]}` and puts a refusal's message in `result`; this path answers the bare result and a refusal as `application/problem+json`.
     */
    post: operations["postNetworkReset"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/bmc/node-to-msd": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Expose a node's storage as a mass-storage device
     * @description Legacy form: `GET /api/bmc?opt=set&type=node_to_msd` with the same parameters in the query string. That form answers `{"response":[{"result":…}]}` and puts a refusal's message in `result`; this path answers the bare result and a refusal as `application/problem+json`.
     */
    post: operations["postNodeToMsd"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/bmc/nodes": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Node names, module names and power-on times
     * @description Legacy form: `GET /api/bmc?opt=get&type=node_info` with the same parameters in the query string. That form answers `{"response":[{"result":…}]}` and puts a refusal's message in `result`; this path answers the bare result and a refusal as `application/problem+json`.
     */
    get: operations["getNodes"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/bmc/ntp": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Time sources and the clock's state
     * @description Legacy form: `GET /api/bmc?opt=get&type=ntp` with the same parameters in the query string. That form answers `{"response":[{"result":…}]}` and puts a refusal's message in `result`; this path answers the bare result and a refusal as `application/problem+json`.
     */
    get: operations["getNtp"];
    put?: never;
    /**
     * Replace the time sources and reload chrony
     * @description Legacy form: `GET /api/bmc?opt=set&type=ntp` with the same parameters in the query string. That form answers `{"response":[{"result":…}]}` and puts a refusal's message in `result`; this path answers the bare result and a refusal as `application/problem+json`.
     */
    post: operations["postNtp"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/bmc/power": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Which nodes are powered
     * @description Legacy form: `GET /api/bmc?opt=get&type=power` with the same parameters in the query string. That form answers `{"response":[{"result":…}]}` and puts a refusal's message in `result`; this path answers the bare result and a refusal as `application/problem+json`.
     */
    get: operations["getPower"];
    put?: never;
    /**
     * Power nodes on or off
     * @description Legacy form: `GET /api/bmc?opt=set&type=power` with the same parameters in the query string. That form answers `{"response":[{"result":…}]}` and puts a refusal's message in `result`; this path answers the bare result and a refusal as `application/problem+json`.
     */
    post: operations["postPower"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/bmc/reboot": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Reboot the BMC; the compute modules keep running
     * @description Legacy form: `GET /api/bmc?opt=set&type=reboot` with the same parameters in the query string. That form answers `{"response":[{"result":…}]}` and puts a refusal's message in `result`; this path answers the bare result and a refusal as `application/problem+json`.
     */
    post: operations["postReboot"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/bmc/reload": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Restart the daemon
     * @description Legacy form: `GET /api/bmc?opt=set&type=reload` with the same parameters in the query string. That form answers `{"response":[{"result":…}]}` and puts a refusal's message in `result`; this path answers the bare result and a refusal as `application/problem+json`.
     */
    post: operations["postReload"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/bmc/reset": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Restart one node
     * @description Legacy form: `GET /api/bmc?opt=set&type=reset` with the same parameters in the query string. That form answers `{"response":[{"result":…}]}` and puts a refusal's message in `result`; this path answers the bare result and a refusal as `application/problem+json`.
     */
    post: operations["postReset"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/bmc/sdcard": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * SD card capacity and use
     * @description Legacy form: `GET /api/bmc?opt=get&type=sdcard` with the same parameters in the query string. That form answers `{"response":[{"result":…}]}` and puts a refusal's message in `result`; this path answers the bare result and a refusal as `application/problem+json`.
     */
    get: operations["getSdcard"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/bmc/sdcard/format": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Format the SD card
     * @description Legacy form: `GET /api/bmc?opt=set&type=sdcard` with the same parameters in the query string. That form answers `{"response":[{"result":…}]}` and puts a refusal's message in `result`; this path answers the bare result and a refusal as `application/problem+json`.
     */
    post: operations["postSdcardFormat"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/bmc/thermal": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Temperature sensors with their trip points, and the fan's step
     * @description Legacy form: `GET /api/bmc?opt=get&type=thermal` with the same parameters in the query string. That form answers `{"response":[{"result":…}]}` and puts a refusal's message in `result`; this path answers the bare result and a refusal as `application/problem+json`.
     */
    get: operations["getThermal"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/bmc/usb": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * The USB bus: which node holds it, in which mode
     * @description Legacy form: `GET /api/bmc?opt=get&type=usb` with the same parameters in the query string. That form answers `{"response":[{"result":…}]}` and puts a refusal's message in `result`; this path answers the bare result and a refusal as `application/problem+json`.
     */
    get: operations["getUsb"];
    put?: never;
    /**
     * Route the USB bus to a node, in a mode
     * @description Legacy form: `GET /api/bmc?opt=set&type=usb` with the same parameters in the query string. That form answers `{"response":[{"result":…}]}` and puts a refusal's message in `result`; this path answers the bare result and a refusal as `application/problem+json`.
     */
    post: operations["postUsb"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/bmc/usb-boot": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Hold a node's usbboot pin for the next power-on
     * @description Legacy form: `GET /api/bmc?opt=set&type=usb_boot` with the same parameters in the query string. That form answers `{"response":[{"result":…}]}` and puts a refusal's message in `result`; this path answers the bare result and a refusal as `application/problem+json`.
     */
    post: operations["postUsbBoot"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/bmc/usb-boot/clear": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Release the usbboot pin
     * @description Legacy form: `GET /api/bmc?opt=set&type=clear_usb_boot` with the same parameters in the query string. That form answers `{"response":[{"result":…}]}` and puts a refusal's message in `result`; this path answers the bare result and a refusal as `application/problem+json`.
     */
    post: operations["postUsbBootClear"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** @description `GET /api/bmc/about` -- what this board and this daemon are. */
    About: {
      /** @description The `/api/bmc` contract version, not a release of anything. */
      api: string;
      bmcd_version: string;
      /**
       * @description From the board's EEPROM. Empty on a board that cannot be read, rather
       *     than absent: upstream's shape, and the interface renders the blank.
       */
      board_model: string;
      board_revision: string;
      /** @description `None` when the EEPROM field is missing or blank after trimming. */
      board_serial?: string | null;
      /**
       * @description The same value as `bmcd_version`. The web interface reads this key for
       *     its "Build version" field and renders `vundefined` without it, so it
       *     is duplicated deliberately rather than left for the client to alias.
       */
      build_version: string;
      buildroot: string;
      buildtime: string;
      hostname: string;
      /**
       * @description The running kernel. `"unknown"` when `uname` cannot be read; the one
       *     field an operator wants after a kernel bump.
       */
      kernel: string;
      /**
       * @description The firmware, from `/etc/os-release`. `"unknown"` when it cannot be
       *     read -- a string, because an About page with a gap is still worth
       *     rendering and this field has never been nullable.
       */
      version: string;
    };
    /**
     * @description `GET /api/bmc/info` -- what the Overview page reads.
     *
     *     Both halves are already typed elsewhere; this names the object that wraps
     *     them so the document has one schema rather than an inline shape.
     */
    BoardInfo: {
      ip: components["schemas"]["NetInfo"][];
      storage: components["schemas"]["StorageInfo"][];
    };
    Candidate: {
      /** @description For a local candidate, the file it came from. */
      file?: string | null;
      prerelease: boolean;
      relation: components["schemas"]["Relation"];
      /** Format: uint64 */
      size_bytes?: number | null;
      trust: components["schemas"]["Trust"];
      version: string;
    };
    Catalog: {
      /**
       * Format: uint64
       * @description How old these answers are. A caller that needs to say "as of a minute
       *     ago" should not have to parse `checked_at` and trust two clocks.
       */
      age_seconds: number;
      checked_at: string;
      /**
       * @description These are the previous answers and a refresh is running behind them.
       *
       *     The page draws a spinner on its "check now" control and leaves the
       *     list underneath readable, rather than blanking or freezing. Skipped
       *     when false so a settled catalogue serialises as it always did.
       */
      refreshing: boolean;
      running: string;
      sources: components["schemas"]["SourceCatalog"][];
    };
    /** @description What one channel resolves to, straight from `tpi-selfupdate --json`. */
    ChannelState: {
      channel: string;
      repo: string;
      running: string;
      target: string;
      update_available: boolean;
    };
    /** @description Whether the board knows what time it is, and how well. */
    Clock: {
      /**
       * @description How the three fields above were obtained, because it is not a file
       *     read like everything else here.
       */
      measured_by?: string | null;
      /**
       * Format: double
       * @description System clock minus true time: negative when the board is behind.
       */
      offset_seconds?: number | null;
      /**
       * @description Every RTC the kernel has. An empty list is a board with none, which
       *     is a board whose clock starts at the epoch on every cold boot.
       */
      rtc: components["schemas"]["Rtc"][];
      /** @description What it is synchronised to, as chrony names it. */
      source?: string | null;
      /** Format: uint32 */
      stratum?: number | null;
      /**
       * @description Whether the system clock is disciplined. `null` when chrony's state
       *     could not be read at all.
       */
      synchronised?: boolean | null;
    };
    ConfigExport: {
      /**
       * @description When and from what. Not read back on import; it is what makes a file
       *     found on a workstation six months later identifiable.
       */
      exported_at: string;
      exported_from: components["schemas"]["ExportOrigin"];
      firmware_sources?: components["schemas"]["Sources"] | null;
      /** Format: uint32 */
      format_version: number;
      hostname?: string | null;
      nodes?: components["schemas"]["NodeSettings"][] | null;
      ntp_servers?: string[] | null;
    };
    /**
     * @description One cooling device: something the thermal framework can turn up, in whole
     *     steps, to cool a zone. On this board that is the fan.
     *
     *     This is deliberately not [`crate::app::cooling_device::CoolingDevice`],
     *     which is the shape `opt=get&type=cooling` has served for years and which
     *     the fan control in the web UI writes back to. That one renames `pwm-fan`
     *     to the platform node behind it and reports the raw steps as `speed` and
     *     `max_speed`. This one passes the kernel's own names and numbers through.
     */
    Cooler: {
      /**
       * Format: uint64
       * @description Which step the device is on right now. Steps are an index, not a
       *     percentage and not an RPM: `4` of `6` is the fifth of seven settings.
       */
      cur_state?: number | null;
      /**
       * @description What each step does, indexed by step: `levels[cur_state]` is the PWM
       *     duty the fan is being driven at, out of the 255 the pwm-fan binding
       *     counts in. Read out of the board's own device tree, so it is a fact
       *     about this board and not a table copied into a client. `None` on a
       *     board that does not describe one, which is not the same as a fan that
       *     runs flat out -- see [`cooling_levels`].
       */
      levels?: number[] | null;
      /**
       * Format: uint32
       * @description The duty at `max_state`, which is the last entry of `levels`: the
       *     denominator for turning a step into a percentage. 254 here, not 255 --
       *     this board's top step is not quite full duty, and saying 255 would be
       *     inventing the difference.
       */
      max_level?: number | null;
      /**
       * Format: uint64
       * @description The highest step it has.
       */
      max_state?: number | null;
      /**
       * @description The device's `type`, as the driver spells it: `pwm-fan`. Falls back to
       *     the directory name.
       */
      name: string;
      /** @description Whether both states were read. */
      present: boolean;
    };
    CoolingDevice: {
      device: string;
      /** Format: uint64 */
      max_speed: number;
      /**
       * @description Whether that zone's governor is paused, which is the only condition
       *     under which a step written here is a step that holds.
       *
       *     With the governor running, `step_wise` returns the fan to the trip the
       *     board is above within a poll, so a written step is a request the
       *     kernel is about to overrule. Reported so a client can say which of
       *     those two things is happening, rather than leaving a person to watch a
       *     slider spring back and draw their own conclusion.
       */
      overridden: boolean;
      /** Format: uint64 */
      speed: number;
      /**
       * @description The thermal zone whose governor drives this device, when one binds it.
       *
       *     A zone binds a cooling device once per trip it should react to, so
       *     this board's single fan is `cdev0` through `cdev3` of the one zone.
       *     Every one of those links is the same answer.
       */
      zone?: string | null;
    };
    ExportOrigin: {
      board_serial?: string | null;
      firmware?: string | null;
      hostname?: string | null;
    };
    /** @description The A/B slot state of the board. */
    FirmwareSlots: {
      /** @description The last line the promotion script wrote, when there is a log. */
      last_promotion?: components["schemas"]["Promotion"] | null;
      /**
       * @description The raw `nextboot` variable when it is set, so a caller can see what
       *     is staged and not merely that something is.
       */
      nextboot?: string | null;
      /**
       * @description Whether the UBI device is there at all. False on a board that boots
       *     from something else, and on any kernel without UBI: the rest of the
       *     fields are then empty because there is nothing to read, not because
       *     something failed.
       */
      present: boolean;
      /**
       * @description How the gate has decided over this board's life. `None` on a board
       *     with no log, which is a board that has never taken an OTA update.
       */
      promotion_history?: components["schemas"]["PromotionHistory"] | null;
      /**
       * @description The slot a rollback would land on, when one can be named without
       *     guessing.
       */
      rollback?: components["schemas"]["Slot"] | null;
      /**
       * @description The slot the board booted from, identified by which volume has an
       *     attached `ubiblock` device.
       */
      running?: components["schemas"]["Slot"] | null;
      /**
       * @description Which image is staged, when whatever staged it left a note. `None`
       *     means no note was found -- on a board where `update_staged` is true
       *     that means the image was staged by something that does not write one,
       *     not that nothing is staged.
       */
      staged?: components["schemas"]["StagedImage"] | null;
      /**
       * @description Whether an update is staged for the next boot. `null` means the
       *     U-Boot environment could not be read at all -- no `fw_printenv` on the
       *     board -- which is not the same as "no update is staged".
       */
      update_staged?: boolean | null;
    };
    /** @description The board's own condition. */
    Health: {
      clock: components["schemas"]["Clock"];
      load: components["schemas"]["Load"];
      memory: components["schemas"]["Memory"];
      nand: components["schemas"]["Nand"];
      /**
       * Format: double
       * @description Seconds since the BMC booted, as `/proc/uptime` gives it. Not the
       *     uptime of any compute module.
       */
      uptime_seconds?: number | null;
    };
    /**
     * @description `GET /api/bmc/hostname` -- live, and after the next boot.
     *
     *     The two differ between a rename and the reboot that settles it, which is
     *     the whole reason both are reported.
     */
    Hostname: {
      /** @description What `sethostname(2)` currently says. `None` if it cannot be read. */
      hostname?: string | null;
      /** @description What `/etc/hostname` holds. `None` when the file is absent. */
      on_next_boot?: string | null;
    };
    /** @description The one-, five- and fifteen-minute load averages. */
    Load: {
      /** Format: double */
      fifteen_minutes?: number | null;
      /** Format: double */
      five_minutes?: number | null;
      /** Format: double */
      one_minute?: number | null;
      /** @description Whether `/proc/loadavg` could be read. */
      present: boolean;
    };
    /**
     * @description Memory, in bytes rather than the kibibytes `/proc/meminfo` speaks.
     *
     *     This is not an academic number on this board. It has 116 MB in total, and
     *     a firmware image being uploaded into `/tmp` is competing with the daemon
     *     for it.
     */
    Memory: {
      /**
       * Format: uint64
       * @description `MemAvailable`: what a new allocation can actually get, reclaim
       *     included. Absent on kernels older than 3.14, which is why it is not
       *     derived from the other two.
       */
      available_bytes?: number | null;
      /** Format: uint64 */
      free_bytes?: number | null;
      /** @description Whether `/proc/meminfo` could be read. */
      present: boolean;
      /**
       * Format: uint64
       * @description This daemon's own resident set, from `/proc/self/statm`.
       *
       *     Board-level memory says the board is being consumed; it cannot say by
       *     what. On 2026-09-09 the board wedged after losing 1 MB a minute under
       *     polling and the metrics could only show the total falling, so the
       *     diagnosis had to be argued from timing rather than read off
       *     (SQU-172). One number closes that gap.
       */
      self_resident_bytes?: number | null;
      /**
       * Format: uint64
       * @description How many threads this daemon has, from `/proc/self/status`.
       *
       *     The companion to the resident set, and the one that says *which kind*
       *     of growth is happening. A heap leak grows the resident set with a flat
       *     thread count; a leaked task or an unreaped blocking thread grows both
       *     together, because every thread carries a stack.
       *
       *     Without it the two are indistinguishable from the outside, which is
       *     the position SQU-172 left us in: memory falling about a megabyte a
       *     minute with no way to say whether it was allocations or threads.
       */
      self_threads?: number | null;
      /** Format: uint64 */
      total_bytes?: number | null;
    };
    /** @description What is left of the NAND, as UBI counts it. */
    Nand: {
      /**
       * Format: uint64
       * @description `available_eraseblocks` in bytes, for callers that would otherwise
       *     multiply the two themselves.
       */
      available_bytes?: number | null;
      /**
       * Format: uint64
       * @description Logical eraseblocks not yet handed to a volume. This is the number
       *     that says whether the next firmware upgrade has room.
       */
      available_eraseblocks?: number | null;
      /**
       * Format: uint64
       * @description Physical eraseblocks the flash has retired.
       */
      bad_eraseblocks?: number | null;
      /** Format: uint64 */
      eraseblock_size_bytes?: number | null;
      /** @description Whether the UBI device is there at all. */
      present: boolean;
      /**
       * Format: uint64
       * @description Physical eraseblocks held back to replace bad ones. When this reaches
       *     zero the next bad block is a failure rather than a substitution.
       */
      reserved_eraseblocks?: number | null;
      /**
       * Format: uint64
       * @description Logical eraseblocks on the device.
       */
      total_eraseblocks?: number | null;
    };
    NetInfo: {
      device: string;
      ip: string;
      mac: string;
    };
    NodeInfo: {
      module_name?: string | null;
      name?: string | null;
      /** Format: uint64 */
      power_on_time?: number | null;
      /** Format: uint32 */
      uart_baud?: number | null;
    };
    /**
     * @description `GET /api/bmc/power` -- one element, four nodes.
     *
     *     Each value is a **string**, not a boolean: `"0"`, `"1"`, or `"Unknown"`
     *     when the daemon could not read the rail. Upstream's shape; a client that
     *     wants a boolean has to handle the third case anyway.
     */
    NodePower: {
      node1: string;
      node2: string;
      node3: string;
      node4: string;
    };
    NodeSettings: {
      /** Format: uint8 */
      id: number;
      module_name?: string | null;
      name?: string | null;
      /** Format: uint32 */
      uart_baud?: number | null;
    };
    /** @description `GET /api/bmc/ntp` -- the time sources, and how the clock is doing. */
    Ntp: {
      clock: components["schemas"]["Clock"];
      /**
       * @description False on an image whose `chrony.conf` predates the `sourcedir` line.
       *     Without it a saved list is written and silently never read, so the
       *     interface must be able to say the setting does nothing.
       */
      configurable: boolean;
      servers: string[];
    };
    /** @description What sits on the other side of a switch port. */
    PortKind: "node" | "uplink";
    /** @description RFC 9457. `detail` is the same message the legacy form puts in `result`. */
    Problem: {
      detail?: string;
      status: number;
      title: string;
      type?: string;
    };
    /** @description What the promotion script last said it did. */
    Promotion: {
      /**
       * @description Everything the script said after its marker. Not classified into
       *     success or failure here, because the vocabulary of that log belongs to
       *     the firmware and not to this daemon.
       */
      message: string;
      /**
       * @description The date the script itself printed, passed through verbatim rather
       *     than reformatted: it is the board's own idea of the time, which on a
       *     BMC that has just come up may be well before the real one.
       */
      timestamp: string;
    };
    /**
     * @description How the health gate has decided, over the life of this board.
     *
     *     The gate's history lived only in `/mnt/overlay/postupdate.log`, so
     *     "nineteen consecutive clean promotions" was a number somebody counted by
     *     hand and wrote on a website, where it went stale the next day.
     */
    PromotionHistory: {
      /**
       * Format: uint64
       * @description Boots that ran the gate at all: one per "tentative boot" line.
       */
      attempts: number;
      /**
       * Format: uint64
       * @description The rest. Derived rather than counted, because the gate has no single
       *     line that means "kept": it can finish through the metrics check, or by
       *     skipping it on a board with no `curl`, or by promoting anyway when
       *     there is no volume to fall back to. Deriving covers all three; the one
       *     inaccuracy is a board cut mid-gate, whose unfinished attempt counts
       *     here. That is rare and errs towards over-reporting success, which is
       *     worth saying out loud in the metric's help text.
       */
      promoted: number;
      /**
       * Format: uint64
       * @description Of those, the ones the gate refused.
       */
      rolled_back: number;
    };
    /**
     * @description How a candidate relates to what is running.
     *
     *     `Unknown` is not a failure. A board built from a working tree reports
     *     `VERSION=local`, and ordering that against real tags is meaningless --
     *     measured on hardware, `sort -V` put `local` first and every release,
     *     including genuinely older code, came out as an upgrade. Saying "unknown" is
     *     the honest answer and lets the page say so rather than implying an order.
     * @enum {string}
     */
    Relation: "current" | "newer" | "older" | "unknown";
    /** @description One real-time clock the kernel has. */
    Rtc: {
      /** @description `rtc0`, `rtc1`. */
      device: string;
      /**
       * @description The driver's own name for it. Which of the two has a battery behind
       *     it is not something the kernel exposes, so it is not claimed here.
       */
      name?: string | null;
    };
    /** @description `GET /api/bmc/sdcard` -- bytes, from `statvfs` on the mount point. */
    SdCard: {
      /** Format: uint64 */
      free: number;
      /** Format: uint64 */
      total: number;
      /**
       * Format: uint64
       * @description Named `use`, not `used`. Upstream's spelling, and a Rust keyword,
       *     which is why the field is renamed rather than called what it means.
       */
      use: number;
    };
    /** @description One firmware slot. */
    Slot: {
      /**
       * Format: uint64
       * @description `data_bytes` of the volume: how much firmware is in it, not how much
       *     space it was given.
       */
      size_bytes?: number | null;
      /**
       * @description Firmware version, and only ever for the running slot. The rollback
       *     volume is not mounted -- nothing on this board reads a squashfs that
       *     is not the root filesystem -- so its `/etc/os-release` is not
       *     reachable, and a version is not guessed from a volume name.
       */
      version?: string | null;
      /** @description UBI volume name, as the volume itself spells it. */
      volume: string;
      /**
       * Format: uint32
       * @description Volume id within the UBI device, the `N` of `ubi0_N`.
       */
      volume_id: number;
    };
    Source: {
      /** @default true */
      enabled: boolean;
      /**
       * @description Stable identifier, used by the install call. Not the label: renaming a
       *     source in the interface must not change what an install refers to.
       */
      id: string;
      kind: components["schemas"]["SourceKind"];
      /** @description What a human calls it. */
      label: string;
      /** @description `owner/repo` for github, a URL prefix for http, a path for local. */
      location: string;
    };
    SourceCatalog: {
      candidates: components["schemas"]["Candidate"][];
      /**
       * @description Why this source produced nothing, when it produced nothing for a
       *     reason. An empty list with no error means the source genuinely offers
       *     nothing; an empty list WITH an error means it could not be read. The
       *     page must not collapse those two into "up to date".
       */
      error?: string | null;
      id: string;
      kind: components["schemas"]["SourceKind"];
      label: string;
      location: string;
    };
    /** @description Where a source's images come from. */
    SourceKind: "github" | "http" | "local";
    Sources: {
      sources: components["schemas"]["Source"][];
    };
    /**
     * @description What is waiting in the staging volume, according to whatever put it there.
     *
     *     Every field is optional because this file is written by something else --
     *     `tpi-selfupdate`, or the daemon's own upgrade worker -- and a marker from
     *     an older writer should degrade to "less is known", never to no answer.
     */
    StagedImage: {
      /**
       * @description The file it came from, when the stager knew a name but not a tag --
       *     an uploaded image whose filename does not follow the release naming
       *     has a file and no version, and saying so beats inventing a version.
       */
      file?: string | null;
      /**
       * @description The checksum the stager verified before writing the volume, so a
       *     caller can tell two builds of one tag apart.
       */
      sha256?: string | null;
      /**
       * @description What staged it -- `tpi-selfupdate`, `upload`. Useful when a board has
       *     a staged image nobody remembers arming.
       */
      source?: string | null;
      /** @description When it was staged, in the board's own idea of the time. */
      staged_at?: string | null;
      /** @description The release tag, as the stager spelled it: `v2.4.0`. */
      version?: string | null;
    };
    StorageInfo: {
      /** Format: uint64 */
      bytes_free: number;
      name: string;
      /** Format: uint64 */
      total_bytes: number;
    };
    /**
     * @description One port of the switch. Every field the kernel would not give us is
     *     `None` rather than a stand-in value: a port that is down has no speed and
     *     no duplex, and saying `0` there would read as a working port running at
     *     nothing.
     */
    SwitchPort: {
      /**
       * @description `full` or `half`. The kernel reports `unknown` for a port with no
       *     link, which becomes `None` here.
       */
      duplex?: string | null;
      kind: components["schemas"]["PortKind"];
      /** @description `carrier`: a peer is electrically there and has trained. */
      link?: boolean | null;
      /** @description Interface name, as the kernel spells it. */
      name: string;
      /**
       * @description `operstate`: `up`, `down`, `lowerlayerdown`, `unknown`. Passed through
       *     verbatim, because the distinction between `down` (nobody asked for the
       *     port) and `lowerlayerdown` (asked for, nothing on the wire) is the
       *     whole point of reading it.
       */
      operstate?: string | null;
      /**
       * @description Whether the kernel has a netdev for this port at all. False means the
       *     switch driver did not register it -- on a board where the driver fails
       *     to probe, all six read false while the BMC itself stays reachable over
       *     its own interface.
       */
      present: boolean;
      /** Format: uint64 */
      rx_bytes?: number | null;
      /** Format: uint64 */
      rx_errors?: number | null;
      /**
       * Format: uint32
       * @description Megabit per second. The kernel reports `-1` for a port with no link,
       *     which becomes `None` here.
       */
      speed_mbps?: number | null;
      /** Format: uint64 */
      tx_bytes?: number | null;
      /** Format: uint64 */
      tx_errors?: number | null;
    };
    /** @description Everything `/sys/class/thermal` has to say. */
    Thermal: {
      cooling: components["schemas"]["Cooler"][];
      sensors: components["schemas"]["ThermalSensor"][];
    };
    /** @description One thermal zone: a sensor the kernel can read a temperature from. */
    ThermalSensor: {
      /**
       * @description The zone's `type`, which is the name its driver registered -- ours is
       *     `bmc-thermal`, from the device tree node. Falls back to the directory
       *     name if the kernel will not answer, so a sensor is never nameless.
       */
      name: string;
      /**
       * @description Whether a temperature was actually read. False is "the zone exists and
       *     the kernel would not tell us", which is not the same as a reading of
       *     zero, and not the same as the zone not existing -- a zone that does not
       *     exist is not in the list at all.
       */
      present: boolean;
      /**
       * Format: double
       * @description Degrees Celsius to one decimal, converted from the millidegrees sysfs
       *     reports. `None` when the zone is there but would not give a reading.
       */
      temperature_c?: number | null;
      /**
       * @description The zone's trip points, in the order the kernel numbers them.
       *
       *     This is what makes the fan's step explicable rather than mysterious.
       *     The governor is `step_wise`, so the step is a consequence of which
       *     trips the board has crossed -- and "the fan is on step 4" with no
       *     reason attached is the question this fork was asked to investigate.
       *     Read from sysfs for the same reason as the cooling levels: it is a
       *     fact about this board, not a table copied into a client.
       */
      trips: components["schemas"]["Trip"][];
    };
    /** @description One trip point: a temperature and what crossing it means. */
    Trip: {
      /**
       * Format: uint32
       * @description The kernel's index for it, which is also its order.
       */
      index: number;
      /**
       * @description `active` drives a cooling device; `hot` and `critical` are the
       *     kernel's own escalations. Passed through as the kernel spells it
       *     rather than mapped, because a client that meets an unfamiliar type
       *     should show it, not swallow it.
       */
      kind?: string | null;
      /** Format: double */
      temperature_c?: number | null;
    };
    /**
     * @description How much is known about an image's integrity.
     *
     *     Three genuinely different things that a page must not render alike: a
     *     checksum published by the release and verified on download; TLS only,
     *     because the publisher ships no checksums at all (upstream's server does
     *     not); and a local file whose provenance is whatever put it there.
     * @enum {string}
     */
    Trust: "verified" | "tls" | "unverified";
    /** @description The answer the API returns. */
    UpdateCheck: {
      /** @description When this was last resolved, in the board's own idea of the time. */
      checked_at: string;
      /** @description The edge channel: the newest release including pre-releases. */
      edge?: components["schemas"]["ChannelState"] | null;
      /**
       * @description Why a channel is missing, when one is. Present WITH a channel too,
       *     when only one of the two could be resolved.
       */
      error?: string | null;
      /** @description The stable channel: what GitHub marks Latest, pre-releases excluded. */
      stable?: components["schemas"]["ChannelState"] | null;
    };
    /** @enum {string} */
    UsbMode: "Host" | "Device" | "Flash";
    /** @enum {string} */
    UsbRoute: "Bmc" | "AlternativePort";
    /** @description `GET /api/bmc/usb` -- which node holds the bus, in which mode. */
    UsbState: {
      /** @description What the hardware is: which of the board's USB controllers is in play. */
      bus_type: string;
      /** @description `Host`, `Device` or `Flash`. */
      mode: components["schemas"]["UsbMode"];
      /** @description The node, as a display string such as `Node 1`. */
      node: string;
      /** @description Where the bus is routed: the alternative port, the BMC, or a node. */
      route: components["schemas"]["UsbRoute"];
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  getAbout: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The result. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["About"];
        };
      };
      /** @description Done, with nothing to report. */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description A refusal, RFC 9457. */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  getConfig: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The result. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ConfigExport"];
        };
      };
      /** @description Done, with nothing to report. */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description A refusal, RFC 9457. */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  postConfig: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Parameters may also be given in the query string; the query string wins on a clash. */
    requestBody?: {
      content: {
        "application/json": {
          /** @description the exported document; a JSON body that is the document itself is accepted as-is */
          config?: string;
        } & {
          [key: string]: unknown;
        };
        "application/x-www-form-urlencoded": {
          /** @description the exported document; a JSON body that is the document itself is accepted as-is */
          config?: string;
        } & {
          [key: string]: unknown;
        };
      };
    };
    responses: {
      /** @description The result. Its shape is not described in this document. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Done, with nothing to report. */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description A refusal, RFC 9457. */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  getCooling: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The result. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CoolingDevice"][];
        };
      };
      /** @description Done, with nothing to report. */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description A refusal, RFC 9457. */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  postCooling: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Parameters may also be given in the query string; the query string wins on a clash. */
    requestBody?: {
      content: {
        "application/json": {
          /** @description as reported by GET /cooling */
          device?: string;
          /** @description a step, 0 to max_speed */
          speed?: string;
        } & {
          [key: string]: unknown;
        };
        "application/x-www-form-urlencoded": {
          /** @description as reported by GET /cooling */
          device?: string;
          /** @description a step, 0 to max_speed */
          speed?: string;
        } & {
          [key: string]: unknown;
        };
      };
    };
    responses: {
      /** @description The result. Its shape is not described in this document. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Done, with nothing to report. */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description A refusal, RFC 9457. */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  getFirmwareAvailable: {
    parameters: {
      query?: {
        /** @description `1` starts a re-poll of every source behind the answer; the answer itself is what was cached */
        refresh?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The result. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Catalog"];
        };
      };
      /** @description Done, with nothing to report. */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description A refusal, RFC 9457. */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  getFirmwareCheck: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The result. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UpdateCheck"];
        };
      };
      /** @description Done, with nothing to report. */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description A refusal, RFC 9457. */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  postFirmwareInstall: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Parameters may also be given in the query string; the query string wins on a clash. */
    requestBody?: {
      content: {
        "application/json": {
          /** @description `1` for a version that is not newer than the running one */
          allow_downgrade?: string;
          /** @description `1` replaces an image that is already staged */
          force?: string;
          /** @description a source id from GET /firmware/sources */
          source?: string;
          /** @description a version that source offers */
          version?: string;
        } & {
          [key: string]: unknown;
        };
        "application/x-www-form-urlencoded": {
          /** @description `1` for a version that is not newer than the running one */
          allow_downgrade?: string;
          /** @description `1` replaces an image that is already staged */
          force?: string;
          /** @description a source id from GET /firmware/sources */
          source?: string;
          /** @description a version that source offers */
          version?: string;
        } & {
          [key: string]: unknown;
        };
      };
    };
    responses: {
      /** @description The result. Its shape is not described in this document. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Done, with nothing to report. */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description A refusal, RFC 9457. */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  getFirmwareSlots: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The result. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["FirmwareSlots"];
        };
      };
      /** @description Done, with nothing to report. */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description A refusal, RFC 9457. */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  getFirmwareSources: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The result. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Sources"];
        };
      };
      /** @description Done, with nothing to report. */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description A refusal, RFC 9457. */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  postFirmwareSources: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Parameters may also be given in the query string; the query string wins on a clash. */
    requestBody?: {
      content: {
        "application/json": {
          /** @description the sources document; a JSON body that is the document itself is accepted as-is */
          sources?: string;
        } & {
          [key: string]: unknown;
        };
        "application/x-www-form-urlencoded": {
          /** @description the sources document; a JSON body that is the document itself is accepted as-is */
          sources?: string;
        } & {
          [key: string]: unknown;
        };
      };
    };
    responses: {
      /** @description The result. Its shape is not described in this document. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Done, with nothing to report. */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description A refusal, RFC 9457. */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  getHealth: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The result. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Health"];
        };
      };
      /** @description Done, with nothing to report. */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description A refusal, RFC 9457. */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  getHostname: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The result. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Hostname"];
        };
      };
      /** @description Done, with nothing to report. */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description A refusal, RFC 9457. */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  postHostname: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Parameters may also be given in the query string; the query string wins on a clash. */
    requestBody?: {
      content: {
        "application/json": {
          /** @description one DNS label: letters, digits, hyphens; no dots */
          name?: string;
        } & {
          [key: string]: unknown;
        };
        "application/x-www-form-urlencoded": {
          /** @description one DNS label: letters, digits, hyphens; no dots */
          name?: string;
        } & {
          [key: string]: unknown;
        };
      };
    };
    responses: {
      /** @description The result. Its shape is not described in this document. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Done, with nothing to report. */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description A refusal, RFC 9457. */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  getInfo: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The result. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["BoardInfo"];
        };
      };
      /** @description Done, with nothing to report. */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description A refusal, RFC 9457. */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  getNetwork: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The result. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            ports: components["schemas"]["SwitchPort"][];
          };
        };
      };
      /** @description Done, with nothing to report. */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description A refusal, RFC 9457. */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  postNetworkReset: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Parameters may also be given in the query string; the query string wins on a clash. */
    requestBody?: {
      content: {
        "application/json": {
          [key: string]: unknown;
        };
        "application/x-www-form-urlencoded": {
          [key: string]: unknown;
        };
      };
    };
    responses: {
      /** @description The result. Its shape is not described in this document. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Done, with nothing to report. */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description A refusal, RFC 9457. */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  postNodeToMsd: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Parameters may also be given in the query string; the query string wins on a clash. */
    requestBody?: {
      content: {
        "application/json": {
          /** @description 1-4 */
          node?: string;
        } & {
          [key: string]: unknown;
        };
        "application/x-www-form-urlencoded": {
          /** @description 1-4 */
          node?: string;
        } & {
          [key: string]: unknown;
        };
      };
    };
    responses: {
      /** @description The result. Its shape is not described in this document. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Done, with nothing to report. */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description A refusal, RFC 9457. */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  getNodes: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The result. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["NodeInfo"][];
        };
      };
      /** @description Done, with nothing to report. */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description A refusal, RFC 9457. */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  getNtp: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The result. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Ntp"];
        };
      };
      /** @description Done, with nothing to report. */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description A refusal, RFC 9457. */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  postNtp: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Parameters may also be given in the query string; the query string wins on a clash. */
    requestBody?: {
      content: {
        "application/json": {
          /** @description comma-separated, in preference order; empty restores the image's pool */
          servers?: string;
        } & {
          [key: string]: unknown;
        };
        "application/x-www-form-urlencoded": {
          /** @description comma-separated, in preference order; empty restores the image's pool */
          servers?: string;
        } & {
          [key: string]: unknown;
        };
      };
    };
    responses: {
      /** @description The result. Its shape is not described in this document. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Done, with nothing to report. */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description A refusal, RFC 9457. */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  getPower: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The result. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["NodePower"][];
        };
      };
      /** @description Done, with nothing to report. */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description A refusal, RFC 9457. */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  postPower: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Parameters may also be given in the query string; the query string wins on a clash. */
    requestBody?: {
      content: {
        "application/json": {
          /** @description 0 or 1 */
          node1?: string;
          /** @description 0 or 1 */
          node2?: string;
          /** @description 0 or 1 */
          node3?: string;
          /** @description 0 or 1 */
          node4?: string;
        } & {
          [key: string]: unknown;
        };
        "application/x-www-form-urlencoded": {
          /** @description 0 or 1 */
          node1?: string;
          /** @description 0 or 1 */
          node2?: string;
          /** @description 0 or 1 */
          node3?: string;
          /** @description 0 or 1 */
          node4?: string;
        } & {
          [key: string]: unknown;
        };
      };
    };
    responses: {
      /** @description The result. Its shape is not described in this document. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Done, with nothing to report. */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description A refusal, RFC 9457. */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  postReboot: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Parameters may also be given in the query string; the query string wins on a clash. */
    requestBody?: {
      content: {
        "application/json": {
          [key: string]: unknown;
        };
        "application/x-www-form-urlencoded": {
          [key: string]: unknown;
        };
      };
    };
    responses: {
      /** @description The result. Its shape is not described in this document. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Done, with nothing to report. */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description A refusal, RFC 9457. */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  postReload: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Parameters may also be given in the query string; the query string wins on a clash. */
    requestBody?: {
      content: {
        "application/json": {
          [key: string]: unknown;
        };
        "application/x-www-form-urlencoded": {
          [key: string]: unknown;
        };
      };
    };
    responses: {
      /** @description The result. Its shape is not described in this document. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Done, with nothing to report. */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description A refusal, RFC 9457. */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  postReset: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Parameters may also be given in the query string; the query string wins on a clash. */
    requestBody?: {
      content: {
        "application/json": {
          /** @description 1-4 */
          node?: string;
        } & {
          [key: string]: unknown;
        };
        "application/x-www-form-urlencoded": {
          /** @description 1-4 */
          node?: string;
        } & {
          [key: string]: unknown;
        };
      };
    };
    responses: {
      /** @description The result. Its shape is not described in this document. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Done, with nothing to report. */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description A refusal, RFC 9457. */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  getSdcard: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The result. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SdCard"][];
        };
      };
      /** @description Done, with nothing to report. */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description A refusal, RFC 9457. */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  postSdcardFormat: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Parameters may also be given in the query string; the query string wins on a clash. */
    requestBody?: {
      content: {
        "application/json": {
          [key: string]: unknown;
        };
        "application/x-www-form-urlencoded": {
          [key: string]: unknown;
        };
      };
    };
    responses: {
      /** @description The result. Its shape is not described in this document. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Done, with nothing to report. */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description A refusal, RFC 9457. */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  getThermal: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The result. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Thermal"];
        };
      };
      /** @description Done, with nothing to report. */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description A refusal, RFC 9457. */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  getUsb: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The result. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UsbState"][];
        };
      };
      /** @description Done, with nothing to report. */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description A refusal, RFC 9457. */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  postUsb: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Parameters may also be given in the query string; the query string wins on a clash. */
    requestBody?: {
      content: {
        "application/json": {
          /** @description 0 host, 1 device, 2 flash */
          mode?: string;
          /** @description 1-4: which node the bus is routed to */
          node?: string;
        } & {
          [key: string]: unknown;
        };
        "application/x-www-form-urlencoded": {
          /** @description 0 host, 1 device, 2 flash */
          mode?: string;
          /** @description 1-4: which node the bus is routed to */
          node?: string;
        } & {
          [key: string]: unknown;
        };
      };
    };
    responses: {
      /** @description The result. Its shape is not described in this document. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Done, with nothing to report. */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description A refusal, RFC 9457. */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  postUsbBoot: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Parameters may also be given in the query string; the query string wins on a clash. */
    requestBody?: {
      content: {
        "application/json": {
          /** @description 1-4 */
          node?: string;
        } & {
          [key: string]: unknown;
        };
        "application/x-www-form-urlencoded": {
          /** @description 1-4 */
          node?: string;
        } & {
          [key: string]: unknown;
        };
      };
    };
    responses: {
      /** @description The result. Its shape is not described in this document. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Done, with nothing to report. */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description A refusal, RFC 9457. */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  postUsbBootClear: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Parameters may also be given in the query string; the query string wins on a clash. */
    requestBody?: {
      content: {
        "application/json": {
          [key: string]: unknown;
        };
        "application/x-www-form-urlencoded": {
          [key: string]: unknown;
        };
      };
    };
    responses: {
      /** @description The result. Its shape is not described in this document. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Done, with nothing to report. */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description A refusal, RFC 9457. */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
}
