apiVersion: v1
kind: Service
metadata:
  name: {{ include "turing-fleet.fullname" . }}
  labels: {{- include "turing-fleet.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      # The image is unprivileged nginx, which listens on 8080 as uid 101.
      targetPort: http
      protocol: TCP
      name: http
  selector: {{- include "turing-fleet.selectorLabels" . | nindent 4 }}
